### PR TITLE
Add an event for when a faction's perms change.

### PR DESCRIPTION
**Pull request by Pokechu22**
This adds an event that fires when a faction's perms are changed using `/f perm set`.

### CODE REVIEW

**Comment by ulumulu1510** [comment]
You commit is styled nicely and codewise it atealst looks fine to me. I guess you took inspiration from the EventFactionsFlagChange, which is great! :)

Have you properly tested this on your local machine? Did you test it on a spigot 1.8.7 release? please give me some information so I know you tested your addition before submiting it :)

**Comment by Pokechu22** [comment]
I did do some testing on my local machine, with a very basic plugin:

```java
public class EventTestStub extends JavaPlugin implements Listener {
	@Override
	public void onEnable() {
		getServer().getPluginManager().registerEvents(this, this);
	}
	
	@EventHandler(priority = EventPriority.MONITOR)
	public void onPermChange(EventFactionsPermChange e) {
		getLogger().info(
				e + " " + e.getFaction() + " " + e.getMSender() + " "
						+ e.getNewValue() + " " + e.getPerm() + " "
						+ e.getRel());
	}
}
```

I didn't test canceling the event yet, though, but I'm 99% sure that what I did should work (mainly because I did mostly use the code from `EventFactionsFlagChange`).  

I did my testing on a spigot 1.8.**3** server, mainly because I haven't ran buildtools in a while on my computer.  I can do testing on 1.8.7, but I'd have to rerun build tools first.

**Comment by ulumulu1510** [comment]
I am quite sure that theEvent will pass the test on 1.8.7 aswell, but please rerun buildtools :) Also, please try canceling, make sure it behaves the way you expected.

**Comment by Pokechu22** [comment]
Just tested it with spigot 1.8.8 (that's what buildtools gave me), and it worked there.  Canceling also worked.

```java
public class EventTestStub extends JavaPlugin implements Listener {
	private boolean cancel = false;
	
	@Override
	public void onEnable() {
		getServer().getPluginManager().registerEvents(this, this);
	}
	
	@EventHandler(priority = EventPriority.MONITOR)
	public void onPermChange(EventFactionsPermChange e) {
		if (cancel) {
			e.getSender().sendMessage(ChatColor.RED + "Your attempt at setting "
					+ "permission " + e.getPerm().getName() + " for " 
					+ e.getRel().getDescPlayerMany() + " "
					+ "to " + e.getNewValue() + " was canceled.");
			e.setCancelled(true);
		} else {
			e.getSender().sendMessage(ChatColor.GREEN + "Your attempt at setting "
					+ "permission " + e.getPerm().getName() + " for " 
					+ e.getRel().getDescPlayerMany() + " "
					+ "to " + e.getNewValue() + " was not canceled.");
		}
		
		cancel = !cancel;
	}
}
```

**Comment by MarkehMe** [comment]
This looks fine to me. Just waiting on approval from @oloflarsson 

:+1:

**Comment by Pokechu22** [comment]
So... is this going to be merged?

**Comment by magnusulf** [comment]
This has been merged, closing.

**Comment by Pokechu22** [comment]
d010cb8a4a2b7bd0bc1c48af422c846d55d4d048, thanks!

**Comment by ulumulu1510** [comment]
Thank you for your work @Pokechu22, we really appreciate it :)

**Pull request closed without merging**
