### PR TITLE
Add missing dependencies and improve lwc dependency

### PR DESCRIPTION
**Pull request by ChrisLane**
Previously factions couldn't be built unless bukkit and vault were
installed via maven already.

This pull request adds bukkit, vault and lwc as external dependencies so
that now only MassiveCore has to be installed by maven (no repo for that
yet :( )

### CODE REVIEW

**Comment by oloflarsson** [comment]
Thanks, I would like to pull this. But I use the spigot-api, not the bukkit one. Are they not two sepparate maven projects?

**Comment by ChrisLane** [comment]
Just changed it to be spigot api.

**Comment by oloflarsson** [comment]
Thanks. Could you squash these commits?

**Comment by ChrisLane** [comment]
Squished commits in new PR

**Pull request closed without merging**
